## Optuna practise

In [1]:
# import necessary linararies
import optuna
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

#load the pima indian dataset from sklearn
#NBote:-Scikit learn built in "load_diabetes"is a regression model
#we will load the actual diabetets from an external source

import pandas as pd
# Load the Pima Indian Diabetes dataset (from UCI repository)
url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv"
columns = ['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI',
           'DiabetesPedigreeFunction', 'Age', 'Outcome']
df=pd.read_csv(url,names=columns)
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [2]:
import numpy as np

# Replace zero values with NaN in columns where zero is not a valid value
cols_with_missing_vals = ['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI']
df[cols_with_missing_vals] = df[cols_with_missing_vals].replace(0, np.nan)

# Impute the missing values with the mean of the respective column
df.fillna(df.mean(), inplace=True)

# Check if there are any remaining missing values
print(df.isnull().sum())

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [3]:
# Split into features (X) and target (y)
X = df.drop('Outcome', axis=1)
y = df['Outcome']

# Split data into training and test sets (70% train, 30% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Optional: Scale the data for better model performance
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Check the shape of the data
print(f'Training set shape: {X_train.shape}')
print(f'Test set shape: {X_test.shape}')

Training set shape: (537, 8)
Test set shape: (231, 8)

In [4]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

# Define the objective function
def objective(trial):
    # Suggest values for the hyperparameters
    n_estimators = trial.suggest_int('n_estimators', 50, 200)
    max_depth = trial.suggest_int('max_depth', 3, 20)

    # Create the RandomForestClassifier with suggested hyperparameters
    model = RandomForestClassifier(
        n_estimators=n_estimators,
        max_depth=max_depth,
        random_state=42
    )

    # Perform 3-fold cross-validation and calculate accuracy
    score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()

    return score  # Return the accuracy score for Optuna to maximize

In [5]:
# Create a study object and optimize the objective function
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.TPESampler())  # We aim to maximize accuracy
study.optimize(objective, n_trials=50)  # Run 50 trials to find the best hyperparameters

[I 2025-11-21 08:41:51,861] A new study created in memory with name: no-name-fdbea03d-6c82-4d9b-9acd-723989c47e4a
[I 2025-11-21 08:41:52,992] Trial 0 finished with value: 0.7541899441340782 and parameters: {'n_estimators': 155, 'max_depth': 3}. Best is trial 0 with value: 0.7541899441340782.
[I 2025-11-21 08:41:54,110] Trial 1 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 162, 'max_depth': 5}. Best is trial 1 with value: 0.7672253258845437.
[I 2025-11-21 08:41:54,906] Trial 2 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 143, 'max_depth': 13}. Best is trial 2 with value: 0.7690875232774674.
[I 2025-11-21 08:41:55,351] Trial 3 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 85, 'max_depth': 5}. Best is trial 2 with value: 0.7690875232774674.
[I 2025-11-21 08:41:56,272] Trial 4 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 191, 'max_depth': 12}. Best is trial 4 with value: 0.7746741154562384.
[I 2025-11-21 08:41:57,046] Trial 5 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 157, 'max_depth': 15}. Best is trial 4 with value: 0.7746741154562384.
[I 2025-11-21 08:41:57,519] Trial 6 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 110, 'max_depth': 5}. Best is trial 4 with value: 0.7746741154562384.
[I 2025-11-21 08:41:57,960] Trial 7 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 98, 'max_depth': 20}. Best is trial 4 with value: 0.7746741154562384.
[I 2025-11-21 08:41:58,468] Trial 8 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 113, 'max_depth': 11}. Best is trial 4 with value: 0.7746741154562384.
[I 2025-11-21 08:41:59,106] Trial 9 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 139, 'max_depth': 17}. Best is trial 4 with value: 0.7746741154562384.
[I 2025-11-21 08:41:59,966] Trial 10 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 191, 'max_depth': 10}. Best is trial 4 with value: 0.7746741154562384.
[I 2025-11-21 08:42:00,832] Trial 11 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 195, 'max_depth': 18}. Best is trial 4 with value: 0.7746741154562384.
[I 2025-11-21 08:42:01,069] Trial 12 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 51, 'max_depth': 16}. Best is trial 4 with value: 0.7746741154562384.
[I 2025-11-21 08:42:01,879] Trial 13 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 180, 'max_depth': 9}. Best is trial 4 with value: 0.7746741154562384.
[I 2025-11-21 08:42:02,472] Trial 14 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 130, 'max_depth': 14}. Best is trial 4 with value: 0.7746741154562384.
[I 2025-11-21 08:42:03,239] Trial 15 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 173, 'max_depth': 17}. Best is trial 4 with value: 0.7746741154562384.
[I 2025-11-21 08:42:03,553] Trial 16 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 68, 'max_depth': 8}. Best is trial 4 with value: 0.7746741154562384.
[I 2025-11-21 08:42:04,175] Trial 17 finished with value: 0.7765363128491619 and parameters: {'n_estimators': 135, 'max_depth': 20}. Best is trial 17 with value: 0.7765363128491619.
[I 2025-11-21 08:42:05,056] Trial 18 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 199, 'max_depth': 20}. Best is trial 17 with value: 0.7765363128491619.
[I 2025-11-21 08:42:05,598] Trial 19 finished with value: 0.7728119180633146 and parameters: {'n_estimators': 122, 'max_depth': 12}. Best is trial 17 with value: 0.7765363128491619.
[I 2025-11-21 08:42:06,490] Trial 20 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 177, 'max_depth': 7}. Best is trial 17 with value: 0.7765363128491619.
[I 2025-11-21 08:42:07,118] Trial 21 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 139, 'max_depth': 18}. Best is trial 17 with value: 0.7765363128491619.
[I 2025-11-21 08:42:07,764] Trial 22 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 145, 'max_depth': 19}. Best is trial 17 with value: 0.7765363128491619.
[I 2025-11-21 08:42:08,173] Trial 23 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 88, 'max_depth': 16}. Best is trial 17 with value: 0.7765363128491619.
[I 2025-11-21 08:42:08,764] Trial 24 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 130, 'max_depth': 14}. Best is trial 17 with value: 0.7765363128491619.
[I 2025-11-21 08:42:09,507] Trial 25 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 165, 'max_depth': 18}. Best is trial 17 with value: 0.7765363128491619.
[I 2025-11-21 08:42:10,005] Trial 26 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 105, 'max_depth': 20}. Best is trial 17 with value: 0.7765363128491619.
[I 2025-11-21 08:42:10,563] Trial 27 finished with value: 0.7783985102420857 and parameters: {'n_estimators': 119, 'max_depth': 16}. Best is trial 27 with value: 0.7783985102420857.
[I 2025-11-21 08:42:11,135] Trial 28 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 120, 'max_depth': 13}. Best is trial 27 with value: 0.7783985102420857.
[I 2025-11-21 08:42:11,562] Trial 29 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 92, 'max_depth': 15}. Best is trial 27 with value: 0.7783985102420857.
[I 2025-11-21 08:42:12,249] Trial 30 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 150, 'max_depth': 11}. Best is trial 27 with value: 0.7783985102420857.
[I 2025-11-21 08:42:12,891] Trial 31 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 136, 'max_depth': 17}. Best is trial 27 with value: 0.7783985102420857.
[I 2025-11-21 08:42:13,599] Trial 32 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 156, 'max_depth': 19}. Best is trial 27 with value: 0.7783985102420857.
[I 2025-11-21 08:42:13,980] Trial 33 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 79, 'max_depth': 16}. Best is trial 27 with value: 0.7783985102420857.
[I 2025-11-21 08:42:14,526] Trial 34 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 117, 'max_depth': 17}. Best is trial 27 with value: 0.7783985102420857.
[I 2025-11-21 08:42:14,977] Trial 35 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 101, 'max_depth': 13}. Best is trial 27 with value: 0.7783985102420857.
[I 2025-11-21 08:42:15,485] Trial 36 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 114, 'max_depth': 19}. Best is trial 27 with value: 0.7783985102420857.
[I 2025-11-21 08:42:15,985] Trial 37 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 114, 'max_depth': 19}. Best is trial 27 with value: 0.7783985102420857.
[I 2025-11-21 08:42:16,523] Trial 38 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 116, 'max_depth': 19}. Best is trial 38 with value: 0.7802607076350093.
[I 2025-11-21 08:42:17,061] Trial 39 finished with value: 0.7839851024208566 and parameters: {'n_estimators': 119, 'max_depth': 15}. Best is trial 39 with value: 0.7839851024208566.
[I 2025-11-21 08:42:17,624] Trial 40 finished with value: 0.7783985102420857 and parameters: {'n_estimators': 122, 'max_depth': 15}. Best is trial 39 with value: 0.7839851024208566.
[I 2025-11-21 08:42:18,175] Trial 41 finished with value: 0.7783985102420857 and parameters: {'n_estimators': 122, 'max_depth': 15}. Best is trial 39 with value: 0.7839851024208566.
[I 2025-11-21 08:42:18,788] Trial 42 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 126, 'max_depth': 14}. Best is trial 39 with value: 0.7839851024208566.
[I 2025-11-21 08:42:19,275] Trial 43 finished with value: 0.7783985102420857 and parameters: {'n_estimators': 106, 'max_depth': 15}. Best is trial 39 with value: 0.7839851024208566.
[I 2025-11-21 08:42:19,723] Trial 44 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 98, 'max_depth': 15}. Best is trial 39 with value: 0.7839851024208566.
[I 2025-11-21 08:42:20,239] Trial 45 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 126, 'max_depth': 3}. Best is trial 39 with value: 0.7839851024208566.
[I 2025-11-21 08:42:20,885] Trial 46 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 148, 'max_depth': 16}. Best is trial 39 with value: 0.7839851024208566.
[I 2025-11-21 08:42:21,372] Trial 47 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 108, 'max_depth': 14}. Best is trial 39 with value: 0.7839851024208566.
[I 2025-11-21 08:42:21,956] Trial 48 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 132, 'max_depth': 12}. Best is trial 39 with value: 0.7839851024208566.
[I 2025-11-21 08:42:22,489] Trial 49 finished with value: 0.7783985102420857 and parameters: {'n_estimators': 120, 'max_depth': 15}. Best is trial 39 with value: 0.7839851024208566.

In [6]:

# Print the best result
print(f'Best trial accuracy: {study.best_trial.value}')
print(f'Best hyperparameters: {study.best_trial.params}')

Best trial accuracy: 0.7839851024208566
Best hyperparameters: {'n_estimators': 119, 'max_depth': 15}

In [7]:
from sklearn.metrics import accuracy_score

# Train a RandomForestClassifier using the best hyperparameters from Optuna
best_model = RandomForestClassifier(**study.best_trial.params, random_state=42)

# Fit the model to the training data
best_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = best_model.predict(X_test)

# Calculate the accuracy on the test set
test_accuracy = accuracy_score(y_test, y_pred)

# Print the test accuracy
print(f'Test Accuracy with best hyperparameters: {test_accuracy:.2f}')

Test Accuracy with best hyperparameters: 0.75

## sampler in Optuna

## for random serach CV

In [8]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

# Define the objective function
def objective(trial):
    # Suggest values for the hyperparameters
    n_estimators = trial.suggest_int('n_estimators', 50, 200)
    max_depth = trial.suggest_int('max_depth', 3, 20)

    # Create the RandomForestClassifier with suggested hyperparameters
    model = RandomForestClassifier(
        n_estimators=n_estimators,
        max_depth=max_depth,
        random_state=42
    )

    # Perform 3-fold cross-validation and calculate accuracy
    score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()

    return score  # Return the accuracy score for Optuna to maximize

In [9]:
# Create a study object and optimize the objective function
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.RandomSampler())  # We aim to maximize accuracy
study.optimize(objective, n_trials=50)  # Run 50 trials to find the best hyperparameters

[I 2025-11-21 08:45:09,203] A new study created in memory with name: no-name-7e7bcf05-779d-41e2-9813-9c42bedbb2ca
[I 2025-11-21 08:45:09,871] Trial 0 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 78, 'max_depth': 17}. Best is trial 0 with value: 0.7653631284916201.
[I 2025-11-21 08:45:10,521] Trial 1 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 84, 'max_depth': 9}. Best is trial 0 with value: 0.7653631284916201.
[I 2025-11-21 08:45:11,623] Trial 2 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 164, 'max_depth': 6}. Best is trial 0 with value: 0.7653631284916201.
[I 2025-11-21 08:45:12,478] Trial 3 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 160, 'max_depth': 13}. Best is trial 3 with value: 0.7690875232774674.
[I 2025-11-21 08:45:13,056] Trial 4 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 125, 'max_depth': 7}. Best is trial 4 with value: 0.7783985102420856.
[I 2025-11-21 08:45:13,513] Trial 5 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 87, 'max_depth': 11}. Best is trial 4 with value: 0.7783985102420856.
[I 2025-11-21 08:45:13,955] Trial 6 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 97, 'max_depth': 14}. Best is trial 4 with value: 0.7783985102420856.
[I 2025-11-21 08:45:14,502] Trial 7 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 122, 'max_depth': 18}. Best is trial 4 with value: 0.7783985102420856.
[I 2025-11-21 08:45:15,262] Trial 8 finished with value: 0.7541899441340782 and parameters: {'n_estimators': 184, 'max_depth': 6}. Best is trial 4 with value: 0.7783985102420856.
[I 2025-11-21 08:45:15,871] Trial 9 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 134, 'max_depth': 12}. Best is trial 4 with value: 0.7783985102420856.
[I 2025-11-21 08:45:16,510] Trial 10 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 138, 'max_depth': 13}. Best is trial 4 with value: 0.7783985102420856.
[I 2025-11-21 08:45:16,957] Trial 11 finished with value: 0.7523277467411544 and parameters: {'n_estimators': 101, 'max_depth': 9}. Best is trial 4 with value: 0.7783985102420856.
[I 2025-11-21 08:45:17,675] Trial 12 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 156, 'max_depth': 18}. Best is trial 4 with value: 0.7783985102420856.
[I 2025-11-21 08:45:18,630] Trial 13 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 174, 'max_depth': 11}. Best is trial 4 with value: 0.7783985102420856.
[I 2025-11-21 08:45:19,123] Trial 14 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 98, 'max_depth': 16}. Best is trial 4 with value: 0.7783985102420856.
[I 2025-11-21 08:45:19,866] Trial 15 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 153, 'max_depth': 12}. Best is trial 4 with value: 0.7783985102420856.
[I 2025-11-21 08:45:20,190] Trial 16 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 64, 'max_depth': 13}. Best is trial 4 with value: 0.7783985102420856.
[I 2025-11-21 08:45:21,096] Trial 17 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 172, 'max_depth': 14}. Best is trial 4 with value: 0.7783985102420856.
[I 2025-11-21 08:45:22,038] Trial 18 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 192, 'max_depth': 15}. Best is trial 4 with value: 0.7783985102420856.
[I 2025-11-21 08:45:22,653] Trial 19 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 139, 'max_depth': 19}. Best is trial 4 with value: 0.7783985102420856.
[I 2025-11-21 08:45:23,361] Trial 20 finished with value: 0.7765363128491619 and parameters: {'n_estimators': 148, 'max_depth': 7}. Best is trial 4 with value: 0.7783985102420856.
[I 2025-11-21 08:45:23,699] Trial 21 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 75, 'max_depth': 8}. Best is trial 4 with value: 0.7783985102420856.
[I 2025-11-21 08:45:24,131] Trial 22 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 101, 'max_depth': 4}. Best is trial 4 with value: 0.7783985102420856.
[I 2025-11-21 08:45:24,822] Trial 23 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 161, 'max_depth': 6}. Best is trial 4 with value: 0.7783985102420856.
[I 2025-11-21 08:45:25,614] Trial 24 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 175, 'max_depth': 20}. Best is trial 4 with value: 0.7783985102420856.
[I 2025-11-21 08:45:26,331] Trial 25 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 164, 'max_depth': 12}. Best is trial 4 with value: 0.7783985102420856.
[I 2025-11-21 08:45:26,934] Trial 26 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 133, 'max_depth': 13}. Best is trial 4 with value: 0.7783985102420856.
[I 2025-11-21 08:45:27,417] Trial 27 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 109, 'max_depth': 20}. Best is trial 4 with value: 0.7783985102420856.
[I 2025-11-21 08:45:28,026] Trial 28 finished with value: 0.7746741154562383 and parameters: {'n_estimators': 137, 'max_depth': 15}. Best is trial 4 with value: 0.7783985102420856.
[I 2025-11-21 08:45:28,700] Trial 29 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 154, 'max_depth': 13}. Best is trial 4 with value: 0.7783985102420856.
[I 2025-11-21 08:45:29,083] Trial 30 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 85, 'max_depth': 15}. Best is trial 4 with value: 0.7783985102420856.
[I 2025-11-21 08:45:29,503] Trial 31 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 95, 'max_depth': 18}. Best is trial 4 with value: 0.7783985102420856.
[I 2025-11-21 08:45:30,333] Trial 32 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 186, 'max_depth': 10}. Best is trial 4 with value: 0.7783985102420856.
[I 2025-11-21 08:45:31,104] Trial 33 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 173, 'max_depth': 16}. Best is trial 4 with value: 0.7783985102420856.
[I 2025-11-21 08:45:31,387] Trial 34 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 62, 'max_depth': 7}. Best is trial 4 with value: 0.7783985102420856.
[I 2025-11-21 08:45:32,157] Trial 35 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 165, 'max_depth': 11}. Best is trial 4 with value: 0.7783985102420856.
[I 2025-11-21 08:45:32,566] Trial 36 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 94, 'max_depth': 8}. Best is trial 4 with value: 0.7783985102420856.
[I 2025-11-21 08:45:33,187] Trial 37 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 123, 'max_depth': 16}. Best is trial 4 with value: 0.7783985102420856.
[I 2025-11-21 08:45:33,510] Trial 38 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 64, 'max_depth': 12}. Best is trial 4 with value: 0.7783985102420856.
[I 2025-11-21 08:45:34,394] Trial 39 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 194, 'max_depth': 14}. Best is trial 4 with value: 0.7783985102420856.
[I 2025-11-21 08:45:34,910] Trial 40 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 118, 'max_depth': 19}. Best is trial 4 with value: 0.7783985102420856.
[I 2025-11-21 08:45:35,618] Trial 41 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 160, 'max_depth': 20}. Best is trial 4 with value: 0.7783985102420856.
[I 2025-11-21 08:45:36,361] Trial 42 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 167, 'max_depth': 13}. Best is trial 4 with value: 0.7783985102420856.
[I 2025-11-21 08:45:37,152] Trial 43 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 180, 'max_depth': 15}. Best is trial 4 with value: 0.7783985102420856.
[I 2025-11-21 08:45:37,701] Trial 44 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 114, 'max_depth': 16}. Best is trial 4 with value: 0.7783985102420856.
[I 2025-11-21 08:45:38,068] Trial 45 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 81, 'max_depth': 18}. Best is trial 4 with value: 0.7783985102420856.
[I 2025-11-21 08:45:38,614] Trial 46 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 121, 'max_depth': 20}. Best is trial 46 with value: 0.7802607076350093.
[I 2025-11-21 08:45:39,431] Trial 47 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 196, 'max_depth': 6}. Best is trial 46 with value: 0.7802607076350093.
[I 2025-11-21 08:45:39,666] Trial 48 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 51, 'max_depth': 19}. Best is trial 46 with value: 0.7802607076350093.
[I 2025-11-21 08:45:39,928] Trial 49 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 58, 'max_depth': 18}. Best is trial 46 with value: 0.7802607076350093.

In [10]:

# Print the best result
print(f'Best trial accuracy: {study.best_trial.value}')
print(f'Best hyperparameters: {study.best_trial.params}')

Best trial accuracy: 0.7802607076350093
Best hyperparameters: {'n_estimators': 121, 'max_depth': 20}

##  For Grid Search CV

In [11]:
# we explctly define searh_space in gridsearchcv
search_space={
    'n_estimators':[50,100,150,200],
    'max_depth':[5,10,15,20]
}

In [12]:
# Create a study object and optimize the objective function
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.GridSampler(search_space))  # We aim to maximize accuracy
study.optimize(objective, n_trials=50)  # Run 50 trials to find the best hyperparameters

[I 2025-11-21 08:46:10,169] A new study created in memory with name: no-name-971ca632-6865-4144-81ae-4e1286337d70
[I 2025-11-21 08:46:10,907] Trial 0 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 100, 'max_depth': 5}. Best is trial 0 with value: 0.7690875232774674.
[I 2025-11-21 08:46:11,834] Trial 1 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 150, 'max_depth': 10}. Best is trial 0 with value: 0.7690875232774674.
[I 2025-11-21 08:46:12,116] Trial 2 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 50, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2025-11-21 08:46:12,590] Trial 3 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 100, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2025-11-21 08:46:13,081] Trial 4 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 100, 'max_depth': 20}. Best is trial 2 with value: 0.7728119180633147.
[I 2025-11-21 08:46:13,373] Trial 5 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 50, 'max_depth': 10}. Best is trial 2 with value: 0.7728119180633147.
[I 2025-11-21 08:46:14,133] Trial 6 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 150, 'max_depth': 5}. Best is trial 2 with value: 0.7728119180633147.
[I 2025-11-21 08:46:14,910] Trial 7 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 150, 'max_depth': 20}. Best is trial 2 with value: 0.7728119180633147.
[I 2025-11-21 08:46:15,626] Trial 8 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 150, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2025-11-21 08:46:16,740] Trial 9 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 200, 'max_depth': 10}. Best is trial 2 with value: 0.7728119180633147.
[I 2025-11-21 08:46:17,848] Trial 10 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 200, 'max_depth': 20}. Best is trial 2 with value: 0.7728119180633147.
[I 2025-11-21 08:46:18,996] Trial 11 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 200, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2025-11-21 08:46:20,120] Trial 12 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 200, 'max_depth': 5}. Best is trial 2 with value: 0.7728119180633147.
[I 2025-11-21 08:46:20,379] Trial 13 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 50, 'max_depth': 5}. Best is trial 13 with value: 0.7746741154562384.
[I 2025-11-21 08:46:20,992] Trial 14 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 100, 'max_depth': 10}. Best is trial 13 with value: 0.7746741154562384.
[I 2025-11-21 08:46:21,252] Trial 15 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 50, 'max_depth': 20}. Best is trial 13 with value: 0.7746741154562384.

In [13]:

# Print the best result
print(f'Best trial accuracy: {study.best_trial.value}')
print(f'Best hyperparameters: {study.best_trial.params}')

Best trial accuracy: 0.7746741154562384
Best hyperparameters: {'n_estimators': 50, 'max_depth': 5}

## Optuna Visualization

In [14]:
# For visualizations
from optuna.visualization import plot_optimization_history, plot_parallel_coordinate, plot_slice, plot_contour, plot_param_importances

In [15]:
#Optimization HIstory
plot_optimization_history(study).show()

In [16]:
# parrallel coodrinate chord
plot_parallel_coordinate(study).show()

In [17]:
#3 sl,ice plot
plot_slice(study).show()

In [18]:
#4 plot contour Plot
plot_contour(study).show()

In [19]:
#5 Hyparameter Importance
plot_param_importances(study).show()

In [20]:
#best thing inoptine
# define by run
# Dynamic Search Species

### Optimizing Multiple ML Models

In [21]:
#library
from sklearn.ensemble import RandomForestClassifier,GradientBoostingClassifier
from sklearn.svm import SVC

In [22]:

#define the obbjection functon for the optima
def objective(trial):
    #choose the algorithm to tune
    classifier_name=trial.suggest_categorical('classifier',['SVM','RandomForest','GradientBoosting'])
    
    if classifier_name == "SVM":
        #SVM Hyperparameter
        c=trial.suggest_float('C',0.1,100,log=True)
        kernel=trial.suggest_categorical('kernel',['linear','rbf','poly','sigmoid'])
        gamma=trial.suggest_categorical('gamma',['scale','auto'])
        model=SVC(C=c,kernel=kernel,gamma=gamma,random_state=42)
        
    elif classifier_name == "RandomForest":
        #random forst hypermeters
        n_estimators=trial.suggest_int('n_estimators',50,300)
        max_depth=trial.suggest_int('max_depth',3,20)
        min_samples_split=trial.suggest_int('min_samples_split',2,10)
        min_samples_leaf=trial.suggest_int('min_samples_leaf',1,10)
        bootstrap=trial.suggest_categorical('bootstrap',[True,False])
        
        model=RandomForestClassifier(
            n_estimators=n_estimators,
            max_depth=max_depth,
            min_samples_split=min_samples_split,
            min_samples_leaf=min_samples_leaf,
            bootstrap=bootstrap,
            random_state=42
        )
    elif classifier_name == 'GradientBoosting':
        # Gradient Boosting hyperparameters
        n_estimators = trial.suggest_int('n_estimators', 50, 300)
        learning_rate = trial.suggest_float('learning_rate', 0.01, 0.3, log=True)
        max_depth = trial.suggest_int('max_depth', 3, 20)
        min_samples_split = trial.suggest_int('min_samples_split', 2, 10)
        min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 10)

        model = GradientBoostingClassifier(
            n_estimators=n_estimators,
            learning_rate=learning_rate,
            max_depth=max_depth,
            min_samples_split=min_samples_split,
            min_samples_leaf=min_samples_leaf,
            random_state=42
        )
        
    # Perform cross-validation and return the mean accuracy
    score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()
    return score

In [23]:
# Create a study and optimize it using CmaEsSampler
study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=100) 
#  default tpe sample

[I 2025-11-21 08:46:23,525] A new study created in memory with name: no-name-12d26751-34a2-43b3-af34-3b269ad95630
[I 2025-11-21 08:46:23,555] Trial 0 finished with value: 0.7318435754189944 and parameters: {'classifier': 'SVM', 'C': 1.55776184714392, 'kernel': 'sigmoid', 'gamma': 'auto'}. Best is trial 0 with value: 0.7318435754189944.
[I 2025-11-21 08:46:23,583] Trial 1 finished with value: 0.7672253258845437 and parameters: {'classifier': 'SVM', 'C': 0.7825676775783441, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 1 with value: 0.7672253258845437.
[I 2025-11-21 08:46:24,869] Trial 2 finished with value: 0.7523277467411545 and parameters: {'classifier': 'RandomForest', 'n_estimators': 271, 'max_depth': 13, 'min_samples_split': 4, 'min_samples_leaf': 9, 'bootstrap': True}. Best is trial 1 with value: 0.7672253258845437.
[I 2025-11-21 08:46:25,711] Trial 3 finished with value: 0.7672253258845437 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 157, 'learning_rate': 0.03633507829090514, 'max_depth': 4, 'min_samples_split': 10, 'min_samples_leaf': 8}. Best is trial 1 with value: 0.7672253258845437.
[I 2025-11-21 08:46:27,832] Trial 4 finished with value: 0.7299813780260708 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 195, 'learning_rate': 0.0995323770269967, 'max_depth': 18, 'min_samples_split': 9, 'min_samples_leaf': 8}. Best is trial 1 with value: 0.7672253258845437.
[I 2025-11-21 08:46:29,036] Trial 5 finished with value: 0.7690875232774674 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 129, 'learning_rate': 0.022604999144458626, 'max_depth': 17, 'min_samples_split': 5, 'min_samples_leaf': 8}. Best is trial 5 with value: 0.7690875232774674.
[I 2025-11-21 08:46:29,948] Trial 6 finished with value: 0.7635009310986964 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 160, 'learning_rate': 0.014043948646887313, 'max_depth': 4, 'min_samples_split': 6, 'min_samples_leaf': 5}. Best is trial 5 with value: 0.7690875232774674.
[I 2025-11-21 08:46:29,972] Trial 7 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.17822170391001155, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 7 with value: 0.7877094972067038.
[I 2025-11-21 08:46:29,994] Trial 8 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.16037115347417188, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 7 with value: 0.7877094972067038.
[I 2025-11-21 08:46:30,535] Trial 9 finished with value: 0.7709497206703911 and parameters: {'classifier': 'RandomForest', 'n_estimators': 130, 'max_depth': 17, 'min_samples_split': 8, 'min_samples_leaf': 5, 'bootstrap': True}. Best is trial 7 with value: 0.7877094972067038.
[I 2025-11-21 08:46:30,697] Trial 10 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 68.07365965767123, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 7 with value: 0.7877094972067038.
[I 2025-11-21 08:46:30,720] Trial 11 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.1164783426454297, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 11 with value: 0.7895716945996275.
[I 2025-11-21 08:46:30,743] Trial 12 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10778996142877796, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 11 with value: 0.7895716945996275.
[I 2025-11-21 08:46:30,766] Trial 13 finished with value: 0.7281191806331471 and parameters: {'classifier': 'SVM', 'C': 0.2918848095644526, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 11 with value: 0.7895716945996275.
[I 2025-11-21 08:46:30,823] Trial 14 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 12.207018156416899, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 11 with value: 0.7895716945996275.
[I 2025-11-21 08:46:30,846] Trial 15 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.44291067842176096, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 11 with value: 0.7895716945996275.
[I 2025-11-21 08:46:31,103] Trial 16 finished with value: 0.7541899441340781 and parameters: {'classifier': 'RandomForest', 'n_estimators': 54, 'max_depth': 9, 'min_samples_split': 2, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 11 with value: 0.7895716945996275.
[I 2025-11-21 08:46:31,150] Trial 17 finished with value: 0.756052141527002 and parameters: {'classifier': 'SVM', 'C': 4.8840667792781485, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 11 with value: 0.7895716945996275.
[I 2025-11-21 08:46:31,186] Trial 18 finished with value: 0.7728119180633147 and parameters: {'classifier': 'SVM', 'C': 0.13162229832134947, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 11 with value: 0.7895716945996275.
[I 2025-11-21 08:46:32,379] Trial 19 finished with value: 0.7746741154562384 and parameters: {'classifier': 'RandomForest', 'n_estimators': 298, 'max_depth': 9, 'min_samples_split': 3, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 11 with value: 0.7895716945996275.
[I 2025-11-21 08:46:32,407] Trial 20 finished with value: 0.7262569832402234 and parameters: {'classifier': 'SVM', 'C': 1.0907392131338236, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 11 with value: 0.7895716945996275.
[I 2025-11-21 08:46:32,437] Trial 21 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.21718197216923216, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 11 with value: 0.7895716945996275.
[I 2025-11-21 08:46:32,464] Trial 22 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.12339252276521064, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 11 with value: 0.7895716945996275.
[I 2025-11-21 08:46:32,489] Trial 23 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.45492494391372723, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 11 with value: 0.7895716945996275.
[I 2025-11-21 08:46:32,515] Trial 24 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10800902328510606, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 11 with value: 0.7895716945996275.
[I 2025-11-21 08:46:32,541] Trial 25 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.4022075969688707, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 11 with value: 0.7895716945996275.
[I 2025-11-21 08:46:32,574] Trial 26 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 3.293482202050701, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 11 with value: 0.7895716945996275.
[I 2025-11-21 08:46:32,605] Trial 27 finished with value: 0.756052141527002 and parameters: {'classifier': 'SVM', 'C': 0.24228000216950332, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 11 with value: 0.7895716945996275.
[I 2025-11-21 08:46:34,282] Trial 28 finished with value: 0.7486033519553073 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 230, 'learning_rate': 0.2723929028049622, 'max_depth': 13, 'min_samples_split': 7, 'min_samples_leaf': 3}. Best is trial 11 with value: 0.7895716945996275.
[I 2025-11-21 08:46:34,603] Trial 29 finished with value: 0.7690875232774674 and parameters: {'classifier': 'RandomForest', 'n_estimators': 57, 'max_depth': 20, 'min_samples_split': 10, 'min_samples_leaf': 10, 'bootstrap': True}. Best is trial 11 with value: 0.7895716945996275.
[I 2025-11-21 08:46:34,628] Trial 30 finished with value: 0.7337057728119181 and parameters: {'classifier': 'SVM', 'C': 0.7260857838461655, 'kernel': 'sigmoid', 'gamma': 'auto'}. Best is trial 11 with value: 0.7895716945996275.
[I 2025-11-21 08:46:34,653] Trial 31 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.19865493297439402, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 11 with value: 0.7895716945996275.
[I 2025-11-21 08:46:34,677] Trial 32 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10535981680131694, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 11 with value: 0.7895716945996275.
[I 2025-11-21 08:46:34,699] Trial 33 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.1863930866283586, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 11 with value: 0.7895716945996275.
[I 2025-11-21 08:46:34,725] Trial 34 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.18332818380626895, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 11 with value: 0.7895716945996275.
[I 2025-11-21 08:46:34,751] Trial 35 finished with value: 0.7337057728119181 and parameters: {'classifier': 'SVM', 'C': 0.3641065765329041, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 11 with value: 0.7895716945996275.
[I 2025-11-21 08:46:35,656] Trial 36 finished with value: 0.7486033519553073 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 96, 'learning_rate': 0.10844399915233503, 'max_depth': 7, 'min_samples_split': 6, 'min_samples_leaf': 3}. Best is trial 11 with value: 0.7895716945996275.
[I 2025-11-21 08:46:35,712] Trial 37 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 12.876150036933275, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 11 with value: 0.7895716945996275.
[I 2025-11-21 08:46:36,586] Trial 38 finished with value: 0.7672253258845437 and parameters: {'classifier': 'RandomForest', 'n_estimators': 215, 'max_depth': 14, 'min_samples_split': 2, 'min_samples_leaf': 6, 'bootstrap': False}. Best is trial 11 with value: 0.7895716945996275.
[I 2025-11-21 08:46:38,273] Trial 39 finished with value: 0.7541899441340782 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 248, 'learning_rate': 0.26090799543751225, 'max_depth': 7, 'min_samples_split': 8, 'min_samples_leaf': 3}. Best is trial 11 with value: 0.7895716945996275.
[I 2025-11-21 08:46:38,298] Trial 40 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.1605160545862274, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 11 with value: 0.7895716945996275.
[I 2025-11-21 08:46:38,324] Trial 41 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10005139147378354, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 11 with value: 0.7895716945996275.
[I 2025-11-21 08:46:38,347] Trial 42 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10232061182759727, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 11 with value: 0.7895716945996275.
[I 2025-11-21 08:46:38,374] Trial 43 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.2792861031827786, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 11 with value: 0.7895716945996275.
[I 2025-11-21 08:46:38,401] Trial 44 finished with value: 0.7746741154562384 and parameters: {'classifier': 'SVM', 'C': 0.14816183763034907, 'kernel': 'sigmoid', 'gamma': 'auto'}. Best is trial 11 with value: 0.7895716945996275.
[I 2025-11-21 08:46:38,427] Trial 45 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.16112239195085845, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 11 with value: 0.7895716945996275.
[I 2025-11-21 08:46:38,456] Trial 46 finished with value: 0.7672253258845437 and parameters: {'classifier': 'SVM', 'C': 0.5625634171937683, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 11 with value: 0.7895716945996275.
[I 2025-11-21 08:46:39,307] Trial 47 finished with value: 0.750465549348231 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 82, 'learning_rate': 0.06710743891159592, 'max_depth': 10, 'min_samples_split': 4, 'min_samples_leaf': 6}. Best is trial 11 with value: 0.7895716945996275.
[I 2025-11-21 08:46:40,477] Trial 48 finished with value: 0.7541899441340782 and parameters: {'classifier': 'RandomForest', 'n_estimators': 299, 'max_depth': 3, 'min_samples_split': 6, 'min_samples_leaf': 10, 'bootstrap': True}. Best is trial 11 with value: 0.7895716945996275.
[I 2025-11-21 08:46:40,505] Trial 49 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.23656604184613206, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 11 with value: 0.7895716945996275.
[I 2025-11-21 08:46:40,539] Trial 50 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 1.9116792392441453, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 11 with value: 0.7895716945996275.
[I 2025-11-21 08:46:40,562] Trial 51 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.1014492718457581, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 11 with value: 0.7895716945996275.
[I 2025-11-21 08:46:40,586] Trial 52 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.1428223439962101, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 11 with value: 0.7895716945996275.
[I 2025-11-21 08:46:40,612] Trial 53 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.2926032318535005, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 11 with value: 0.7895716945996275.
[I 2025-11-21 08:46:40,638] Trial 54 finished with value: 0.7113594040968342 and parameters: {'classifier': 'SVM', 'C': 0.14297448117425388, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 11 with value: 0.7895716945996275.
[I 2025-11-21 08:46:40,661] Trial 55 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.3133598297072359, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 11 with value: 0.7895716945996275.
[I 2025-11-21 08:46:40,780] Trial 56 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 33.0700333542745, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 11 with value: 0.7895716945996275.
[I 2025-11-21 08:46:40,809] Trial 57 finished with value: 0.7709497206703911 and parameters: {'classifier': 'SVM', 'C': 0.1528950337495557, 'kernel': 'sigmoid', 'gamma': 'auto'}. Best is trial 11 with value: 0.7895716945996275.
[I 2025-11-21 08:46:41,585] Trial 58 finished with value: 0.7709497206703911 and parameters: {'classifier': 'RandomForest', 'n_estimators': 190, 'max_depth': 6, 'min_samples_split': 4, 'min_samples_leaf': 4, 'bootstrap': False}. Best is trial 11 with value: 0.7895716945996275.
[I 2025-11-21 08:46:41,620] Trial 59 finished with value: 0.7653631284916201 and parameters: {'classifier': 'SVM', 'C': 0.554398310258464, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 11 with value: 0.7895716945996275.
[I 2025-11-21 08:46:42,937] Trial 60 finished with value: 0.7579143389199254 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 120, 'learning_rate': 0.010118219404859062, 'max_depth': 15, 'min_samples_split': 7, 'min_samples_leaf': 7}. Best is trial 11 with value: 0.7895716945996275.
[I 2025-11-21 08:46:42,965] Trial 61 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.12785497727306022, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 11 with value: 0.7895716945996275.
[I 2025-11-21 08:46:42,991] Trial 62 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.1335922256517995, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 11 with value: 0.7895716945996275.
[I 2025-11-21 08:46:43,019] Trial 63 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.2112716925318522, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 11 with value: 0.7895716945996275.
[I 2025-11-21 08:46:43,047] Trial 64 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.14183908245437987, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 11 with value: 0.7895716945996275.
[I 2025-11-21 08:46:43,077] Trial 65 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.12812808668292497, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 11 with value: 0.7895716945996275.
[I 2025-11-21 08:46:43,103] Trial 66 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.14076979323171504, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 11 with value: 0.7895716945996275.
[I 2025-11-21 08:46:43,132] Trial 67 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.12910257536423844, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 11 with value: 0.7895716945996275.
[I 2025-11-21 08:46:43,160] Trial 68 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.23572130124410862, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 11 with value: 0.7895716945996275.
[I 2025-11-21 08:46:43,191] Trial 69 finished with value: 0.7113594040968342 and parameters: {'classifier': 'SVM', 'C': 0.13689427745440153, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 11 with value: 0.7895716945996275.
[I 2025-11-21 08:46:43,220] Trial 70 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.19033316918832904, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 11 with value: 0.7895716945996275.
[I 2025-11-21 08:46:43,253] Trial 71 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.1297065753711349, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 11 with value: 0.7895716945996275.
[I 2025-11-21 08:46:43,292] Trial 72 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.1251244559537101, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 11 with value: 0.7895716945996275.
[I 2025-11-21 08:46:43,319] Trial 73 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.33233064763648273, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 11 with value: 0.7895716945996275.
[I 2025-11-21 08:46:43,351] Trial 74 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.17897521413354983, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 11 with value: 0.7895716945996275.
[I 2025-11-21 08:46:43,380] Trial 75 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.24996700710506384, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 11 with value: 0.7895716945996275.
[I 2025-11-21 08:46:43,405] Trial 76 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.12273627020896409, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 11 with value: 0.7895716945996275.
[I 2025-11-21 08:46:44,562] Trial 77 finished with value: 0.7597765363128491 and parameters: {'classifier': 'RandomForest', 'n_estimators': 256, 'max_depth': 20, 'min_samples_split': 9, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 11 with value: 0.7895716945996275.
[I 2025-11-21 08:46:44,595] Trial 78 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 1.213003733849352, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 11 with value: 0.7895716945996275.
[I 2025-11-21 08:46:44,632] Trial 79 finished with value: 0.7523277467411545 and parameters: {'classifier': 'SVM', 'C': 7.113488497422636, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 11 with value: 0.7895716945996275.
[I 2025-11-21 08:46:46,301] Trial 80 finished with value: 0.7355679702048418 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 88, 'learning_rate': 0.0384707874937263, 'max_depth': 11, 'min_samples_split': 3, 'min_samples_leaf': 2}. Best is trial 11 with value: 0.7895716945996275.
[I 2025-11-21 08:46:46,324] Trial 81 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.13012189684234904, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 11 with value: 0.7895716945996275.

In [24]:
# Retrieve the best trial
best_trial = study.best_trial
print("Best trial parameters:", best_trial.params)
print("Best trial accuracy:", best_trial.value)

Best trial parameters: {'classifier': 'SVM', 'C': 0.1164783426454297, 'kernel': 'linear', 'gamma': 'auto'}
Best trial accuracy: 0.7895716945996275

In [25]:
study.trials_dataframe()

,number,value,datetime_start,datetime_complete,duration,params_C,params_bootstrap,params_classifier,params_gamma,params_kernel,params_learning_rate,params_max_depth,params_min_samples_leaf,params_min_samples_split,params_n_estimators,state
0,0,0.731844,2025-11-21 08:46:23.526879,2025-11-21 08:46:23.555706,0 days 00:00:00.028827,1.557762,NaN,SVM,auto,sigmoid,NaN,NaN,NaN,NaN,NaN,COMPLETE
1,1,0.767225,2025-11-21 08:46:23.557257,2025-11-21 08:46:23.583622,0 days 00:00:00.026365,0.782568,NaN,SVM,auto,rbf,NaN,NaN,NaN,NaN,NaN,COMPLETE
2,2,0.752328,2025-11-21 08:46:23.583622,2025-11-21 08:46:24.869528,0 days 00:00:01.285906,NaN,True,RandomForest,NaN,NaN,NaN,13.0,9.0,4.0,271.0,COMPLETE
3,3,0.767225,2025-11-21 08:46:24.870543,2025-11-21 08:46:25.711252,0 days 00:00:00.840709,NaN,NaN,GradientBoosting,NaN,NaN,0.036335,4.0,8.0,10.0,157.0,COMPLETE
4,4,0.729981,2025-11-21 08:46:25.713233,2025-11-21 08:46:27.832308,0 days 00:00:02.119075,NaN,NaN,GradientBoosting,NaN,NaN,0.099532,18.0,8.0,9.0,195.0,COMPLETE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,95,0.789572,2025-11-21 08:46:46.911145,2025-11-21 08:46:46.935563,0 days 00:00:00.024418,0.115858,NaN,SVM,auto,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE
96,96,0.772812,2025-11-21 08:46:46.936573,2025-11-21 08:46:47.550409,0 days 00:00:00.613836,NaN,False,RandomForest,NaN,NaN,NaN,15.0,7.0,5.0,164.0,COMPLETE
97,97,0.787709,2025-11-21 08:46:47.551393,2025-11-21 08:46:47.577881,0 days 00:00:00.026488,0.174376,NaN,SVM,scale,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE
98,98,0.744879,2025-11-21 08:46:47.578904,2025-11-21 08:46:49.341869,0 days 00:00:01.762965,NaN,NaN,GradientBoosting,NaN,NaN,0.159095,6.0,4.0,8.0,212.0,COMPLETE
99,99,0.789572,2025-11-21 08:46:49.343867,2025-11-21 08:46:49.371817,0 days 00:00:00.027950,0.149303,NaN,SVM,auto,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE

In [26]:
study.trials_dataframe()['params_classifier'].value_counts()

params_classifier
SVM                 79
GradientBoosting    11
RandomForest        10
Name: count, dtype: int64

In [27]:
study.trials_dataframe().groupby('params_classifier')['value'].mean()

params_classifier
GradientBoosting    0.751820
RandomForest        0.764618
SVM                 0.778304
Name: value, dtype: float64